<div class="page-header">
	<div class="btn-group pull-right">
		<!-- <a href="#delete-user" class="btn btn-danger" data-toggle="modal"><i class="icon-white icon-remove"></i> Delete user</a> -->
		<!-- <a href="#" class="btn"><i class="icon-download"></i> Download user profile</a> -->
	</div>

	<h2><?php echo $this->auth()->username; ?> <small>&lsaquo; <?php echo $this->auth()->firstname . ' ' . $this->auth()->lastname; ?> &rsaquo;</small></h2>
</div>

<?php echo $this->form; ?>